@echo off
set PYTHONPATH=libs\aja-core
set GEMINI_API_KEY=REDACTED_GEMINI_KEY
set GOOGLE_API_KEY=REDACTED_GEMINI_KEY
set OPENBLAS_NUM_THREADS=1
set OPENBLAS_MAIN_FREE=1
set KMP_DUPLICATE_LIB_OK=TRUE
set OMP_NUM_THREADS=1
set MKL_NUM_THREADS=1
set PYTHONUNBUFFERED=1
set PYTHONIOENCODING=utf-8

echo [DEBUG] Starting Autonomous Worker only...
python -m aja.runtime.autonomous_loop
