"""Client memory bridge route paths backed by the current Lance store."""

ROUTE_PATHS = (
    "/workers",
    "/workers/{worker_id}",
    "/workers/seed",
    "/workers/recommend",
    "/workers/{worker_id}/history",
    "/workers/{worker_id}/log",
    "/priority/engine",
    "/memory/tasks",
    "/memory/tasks/{task_id}",
    "/memory/tasks/{task_id}/complete",
    "/memory/tasks/{task_id}/archive",
    "/memory/review",
    "/memory/summary",
    "/communications",
    "/communications/{message_id}",
    "/communications/{message_id}/edit",
    "/communications/{message_id}/approve",
    "/communications/{message_id}/reject",
    "/communications/{message_id}/send",
    "/communications/summary/mobile",
    "/scheduler/config",
    "/scheduler/review/{kind}",
    "/scheduler/review/{kind}/deliver",
    "/scheduler/run",
    "/scheduler/snooze/{task_id}",
)
